<!-- build:js(/Volumes/Chases/noaa/) foot-videojs.combined.min.js -->    
    <!-- FOOT - VIDEO JS --> 
        <!-- <script src="/js/video-js/7.6.6/video.min.js"></script> --> 
        <!-- <script src="/js/video-js/7.6.6/videojs-resolution-switcher.min.js"></script> --> 
        <!-- <script src="/js/video-js/7.6.6/videojs-init.min.js"></script> --> 
    <script src="/js/video.min.js"></script>
    <script src="/js/videojs-resolution-switcher.min.js"></script>
    <script src="/js/videojs-init.min.js"></script>
    <!-- endbuild -->