<!--include virtual="/include1/head-global-bs4.5-dev.inc" | HEAD - GLOBAL STYLES (Bootstrap 4.5) -->
<!-- Framework -->
<link rel="stylesheet" href="/css/bootstrap-4.5.2/css/bootstrap.css">
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/responsive.css">
<!-- font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />