<!--include virtual="/include1/head-global-bs4.5.inc" | HEAD - GLOBAL STYLES (Bootstrap 4.5) -->
    <!-- Framework -->
    <link rel="stylesheet" href="/css/bootstrap-4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.min.css">
    <link rel="stylesheet" href="/css/responsive.min.css">
    <!-- font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />
    <!--end include-->