<!--include virtual="/include1/superfoot-videojs-map-dev.inc" | FOOT - VIDEO - MAP - NO PORTFOLIO (welcome - videojs - with dives) -->
<!-- VideoJS -->
<script src="/js/video.min.js"></script>
<script src="/js/videojs-resolution-switcher.min.js"></script>
<script src="/js/videojs-init.min.js"></script>
<!-- Global Scripts -->   
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-latest.min.js"></script>
<!-- Bootstrap -->
<script src="/js/bootstrap.min.js"></script>
<script src="/js/bootstrap-hover-dropdown.min.js"></script>
<script src="/js/nav.min.js"></script>
<!-- Back to Top script -->
<script src="/js/back-to-top.min.js"></script>
<!-- Google Tag Manager -->
<script src="/js/google.tag.manager.min.js"></script>
<!-- Google Analytics -->
<script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script>
<script src="/js/google.analytics.min.js"></script> 
<!-- MAP -->
<script src="/js/jquery-activmap.min.js"></script>
<script src="/js/markercluster.min.js"></script>    
<script src="https://maps.googleapis.com/maps/api/js?libraries=visualization&v=3&client=gme-noaa&channel=OAR.OER.APP.Test"></script>