<!--include virtual="/include1/superfoot-dayfolio-map.inc" | FOOT - PORTFOLIO - DAILYUPDATES STYLE - MAP - NO VIDEO (dailyupdates with dives) CBP ARGS -->
<!-- jQuery -->
<script src="https://code.jquery.com/jquery-latest.min.js"></script>
<!-- Bootstrap -->
<script src="/js/bootstrap.min.js"></script>
<script src="/js/bootstrap-hover-dropdown.min.js"></script>
<script src="/js/nav.min.js"></script>
<!-- Back to Top script -->
<script src="/js/back-to-top.min.js"></script>
<!-- Google Tag Manager -->
<script src="/js/google.tag.manager.min.js"></script>
<!-- Google Analytics -->
<script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script>
<script src="/js/google.analytics.min.js"></script>
<!-- CBP -->  
<script src="/cubeportfolio/js/jquery.cubeportfolio.min.js"></script>
<script src="/js/cbp-init-args.min.js"></script>
<!-- MAP -->
<script src="/js/jquery-activmap.min.js"></script>
<script src="/js/markercluster.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?libraries=visualization&v=3&client=gme-noaa&channel=OAR.OER.APP.Test"></script>