<!--include virtual="/include1/superfoot-portfolio-video.inc" | FOOT - PORTFOLIO - PHOTOLOG STYLE - VIDEO - NO MAP (photolog - jwplayer) -->
    <!-- Bootstrap -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-hover-dropdown.min.js"></script>
    <script src="/js/nav.min.js"></script>
    <!-- Back to Top script -->
    <script src="/js/back-to-top.min.js"></script>
    <!-- Google Tag Manager -->
    <script src="/js/google.tag.manager.min.js"></script>
    <!-- Google Analytics -->
    <script id="_fed_an_ua_tag" src="/js/universal.federated.analytics.min.js?agency=DOC&subagency=NOAA"></script>
    <script src="/js/google.analytics.min.js"></script>   
    <!-- CBP -->  
    <script src="/cubeportfolio/js/jquery.cubeportfolio.4.4.0.min.js"></script>
    <script src="/js/cbp-init-args.min.js"></script>    
    <!-- JWPlayer -->
    <script src="/js/one-vid.min.js"></script>
    <!--end include-->