<!-- build:css(/Volumes/Chases/noaa/) head-videojs.combined.min.css -->
    <!-- HEAD VIDEO JS -->  
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/video-js.min.css"/> -->
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/videojs-resolution-switcher.min.css"/> -->
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/videojs-oer.min.css"/> -->
    <link rel="stylesheet" href="/css/video-js.min.css"/>
    <link rel="stylesheet" href="/css/videojs-resolution-switcher.min.css"/>
    <link rel="stylesheet" href="/css/videojs-oer.min.css"/>
    <!-- endbuild -->