<!-- build:css(/Volumes/Chases/noaa/) superhead-dailyfolio-map.combined.min.css -->
    <!-- HEAD - PORTFOLIO - DAILYUPDATES STYLE - MAP - NO VIDEO (dailyupdates - with dives) -->
    <!-- CBP -->
        <!-- <link rel="stylesheet" href="/css/cubeportfolio/4.4.0/cubeportfolio.dailyupdates.min.css"> -->
    <link rel="stylesheet" href="/cubeportfolio/css/cubeportfolio_dailyupdates.min.css">
    <!-- Map -->
        <!-- <link rel="stylesheet" href="/css/jquery-activmap/1.7.1/jquery-activmap.min.css"> -->
    <link rel="stylesheet" href="/css/jquery-activmap.min.css" />
    <!-- Framework -->
        <!-- <link rel="stylesheet" href="/css/bootstrap/3.3.7/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/jquery/responsive.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/utilities/style.min.css"> -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/responsive.min.css">
    <link rel="stylesheet" href="/css/style.min.css">  
    <!-- endbuild -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />