<!-- build:js(/Volumes/Chases/noaa/) superhead-portfolio-video.combined.min.js -->
    <!-- HEAD - PORTFOLIO - PHOTOLOG STYLE - VIDEO - NO MAP (photolog - jwplayer) -->
    <!-- jQuery -->
        <!-- <script src="/js/jquery/1.11.3/jquery.min.js"></script> -->
    <script src="/js/jquery.min.js"></script>
    <!-- JWPlayer -->
        <!-- <script src="/js/jwplayer/5.0.0/jwplayer.min.js"></script> -->
    <script src="/js/jwplayer.min.js"></script> 
    <!-- endbuild -->    
    <script>jwplayer.key="Xn/dEFaxTQlMV6FC3sSXmvmPbX7BCdZdGOcUGey7Aos=";</script>
    <!-- build:css(/Volumes/Chases/noaa/) superhead-portfolio-video.combined.min.css -->
    <!-- CBP -->
        <!-- <link rel="stylesheet" href="/css/cubeportfolio/4.4.0/cubeportfolio.min.css"> -->
    <link rel="stylesheet" href="/cubeportfolio/css/cubeportfolio.4.4.0.min.css">
    <!-- Framework -->
        <!-- <link rel="stylesheet" href="/css/bootstrap/3.3.7/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/jquery/responsive.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/utilities/style.min.css"> -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/responsive.min.css">
    <link rel="stylesheet" href="/css/style.min.css">   
    <!-- endbuild -->    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />