<!-- build:css(/Volumes/Chases/noaa/) superhead-portfolio-videojs.combined.min.css -->
    <!-- HEAD - PORTFOLIO - VIDEO - NO MAP (photolog - videojs) -->
    <!-- VideoJS -->
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/video-js.min.css"/> -->
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/videojs-resolution-switcher.min.css"/> -->
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/videojs-oer.min.css"/> -->
    <link rel="stylesheet" href="/css/video-js.min.css"/>
    <link rel="stylesheet" href="/css/videojs-resolution-switcher.min.css"/>
    <link rel="stylesheet" href="/css/videojs-oer.min.css"/>
    <!-- CBP -->
        <!-- <link rel="stylesheet" href="/css/cubeportfolio/4.4.0/cubeportfolio.min.css"> -->
    <link rel="stylesheet" href="/cubeportfolio/css/cubeportfolio.4.4.0.min.css">
    <!-- Framework -->
        <!-- <link rel="stylesheet" href="/css/bootstrap/3.3.7/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/jquery/responsive.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/utilities/style.min.css"> -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/responsive.min.css">
    <link rel="stylesheet" href="/css/style.min.css">
    <!-- endbuild -->    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />