<!-- build:css(/Volumes/Chases/noaa/) superhead-videojs.combined.min.css -->
    <!-- HEAD - VIDEO - NO MAP - NO PORTFOLIO (general - videojs) -->
    <!-- VideoJS -->
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/video-js.min.css"/> -->
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/videojs-resolution-switcher.min.css"/> -->
        <!-- <link rel="stylesheet" href="/css/video-js/7.6.6/videojs-oer.min.css"/> -->
    <link rel="stylesheet" href="/css/video-js.min.css"/>
    <link rel="stylesheet" href="/css/videojs-resolution-switcher.min.css"/>
    <link rel="stylesheet" href="/css/videojs-oer.min.css"/>
    <!-- Framework -->
        <!-- <link rel="stylesheet" href="/css/bootstrap/3.3.7/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/jquery/responsive.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/utilities/style.min.css"> -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/responsive.min.css">
    <link rel="stylesheet" href="/css/style.min.css">
    <!-- endbuild -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />