<!-- build:js(/Volumes/Chases/noaa/) superhead-video-map.combined.min.js -->
    <!-- HEAD - VIDEO - MAP - NO PORTFOLIO (welcome - jwplayer - with dives) -->
    <!-- jQuery -->
        <!-- <script src="/js/jquery/1.11.3/jquery.min.js"></script> -->
    <script src="/js/jquery.min.js"></script>
    <!-- JWPlayer -->
        <!-- <script src="/js/jwplayer/5.0.0/jwplayer.min.js"></script> -->
    <script src="/js/jwplayer.min.js"></script>
    <!-- endbuild -->
    <!-- build:css(/Volumes/Chases/noaa/) superhead-video-map.combined.min.css -->
    <!-- Map -->
        <!-- <link rel="stylesheet" href="/css/jquery-activmap/1.7.1/jquery-activmap.min.css"> -->
    <link rel="stylesheet" href="/css/jquery-activmap.min.css" />
    <!-- Framework -->
        <!-- <link rel="stylesheet" href="/css/bootstrap/3.3.7/bootstrap.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/jquery/responsive.min.css"> -->
        <!-- <link rel="stylesheet" href="/css/utilities/style.min.css"> -->
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/responsive.min.css">
    <link rel="stylesheet" href="/css/style.min.css">
    <!-- endbuild -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700%7CRoboto+Slab:400,700" />